### ISSUE TITLE
Sending new token on every request

### ISSUE THREAD

**Issue by varukashotta** [gage-langdon/graphql-connect#3]
hello 

thank you for the extension, would like to ask how to add a header token on every request

Thank you

**Comment by gage-langdon** [comment]
@varukashotta So sorry! Did not see your issue, guess my notifications were turned off or something. You will need to set new headers on outgoing requests just like you do the first one, but make sure not to cache  the remote client. 

Have you tried this and its not working? Let me know, ill fix my notification settings now.
